paths:
  model_output: /data/c-sniderb/a5-alignment/grpo-experiments/off_policy_sweep/e1_bs_256_mean

training:
  n_grpo_steps: 50
  gradient_accumulation_steps: 128
  epochs_per_rollout_batch: 1
  train_batch_size: 256
  loss_type: grpo_clip
  normalize_mode: mean
  wandb_tags:
    - grpo
    - off-policy-sweep