paths:
  model_output: /data/c-sniderb/a5-alignment/grpo-experiments/off_policy_sweep/e1_bs_32

training:
  n_grpo_steps: 50
  gradient_accumulation_steps: 16
  epochs_per_rollout_batch: 1
  train_batch_size: 32
  loss_type: grpo_clip
  wandb_tags:
    - grpo
    - off-policy-sweep