paths:
  model_output: /data/c-sniderb/a5-alignment/grpo-experiments/off_policy_sweep/e1_bs128_no_std_dev

training:
  n_grpo_steps: 50
  gradient_accumulation_steps: 64
  epochs_per_rollout_batch: 1
  train_batch_size: 128
  loss_type: grpo_clip
  use_std_normalization: False
  wandb_tags:
    - grpo
    - off-policy-sweep