paths:
  model_output: /data/c-sniderb/a5-alignment/grpo-experiments/off_policy_sweep/e4_bs_128

training:
  n_grpo_steps: 50
  gradient_accumulation_steps: 64
  epochs_per_rollout_batch: 4
  train_batch_size: 128
  loss_type: grpo_clip
  wandb_tags:
    - grpo
    - off-policy-sweep