paths:
  model_output: /data/c-sniderb/a5-alignment/grpo-experiments/group_std_dev/no_std_dev_constant_3e-5

training:
  use_std_normalization: False
  learning_rate: 3e-5
  normalize_mode: constant
  wandb_tags:
    - grpo
    - group_std_dev