paths:
  model_output: /data/c-sniderb/a5-alignment/leaderboard/004_constant_2e-5

training:
  learning_rate: 2e-5
  n_grpo_steps: 50
  normalize_mode: "constant"
  wandb_tags:
    - grpo
    - leaderboard
