paths:
  model_output: /data/c-sniderb/a5-alignment/leaderboard/008_microbatch_3e-5

training:
  learning_rate: 3e-5
  n_grpo_steps: 50
  normalize_mode: "microbatch"
  wandb_tags:
    - grpo
    - leaderboard