paths:
  model_output: /data/c-sniderb/a5-alignment/grpo-experiments/baselines/reinforce_with_baseline

training:
  loss_type: reinforce_with_baseline
  normalize_mode: mean
  wandb_tags:
    - grpo
    - baselines